In [1]:
import numpy as np

List vs Numpy -Time taken

In [2]:
from time import process_time

time taken by list

In [7]:
python_list = [i for i in range(10000)]
start_time = process_time()
python_list = [i +5 for i in python_list]
end_time = process_time()
print(end_time- start_time)

0.0007371229999986184


In [8]:
np_arry = np.array([i for i in range(10000)])
start_time = process_time()
np_arry += 5
end_time = process_time()
print(end_time- start_time)

0.00016277499999972633


Numpy arrays

In [10]:
#list
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [11]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [14]:
b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [15]:
b.shape

(2, 4)

In [16]:
c = np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


initial place holders in numpy arrays


In [18]:
#create a numpy array of zeros
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [19]:
x = np.ones((4,5))
print(x)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [20]:
x = np.full((4,5),3)
print(x)

[[3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]]


In [23]:
#create a identity matrix
a = np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [26]:
#create a numpy array with random values
b = np.random.random((3,4))
print(b)

[[0.93013417 0.65623332 0.25617071 0.99727898]
 [0.69142585 0.69078007 0.79399168 0.68615308]
 [0.03981826 0.6413871  0.23451854 0.24328373]]


In [28]:
#random integer values array , withing. a spectific range

c = np.random.randint(10,200,(3,4))
print(c)

[[194 128  83 169]
 [ 63  17 190 109]
 [ 98  99  78  15]]


In [30]:
#create  an array of evenly spaced values
d = np.linspace(10,30,5)
print(d)

[10. 15. 20. 25. 30.]


In [32]:
#array of evenly spaced values  --> specifying the step

e = np.arange(10, 30 , 5)
print(e)

[10 15 20 25]


In [35]:
#convert a list to NP array
list2 = [10,20,30,40,50]
np_array = np.array(list2)
print(np_array)
type(np_array)

[10 20 30 40 50]


numpy.ndarray

In [36]:
c = np.random.randint(10, 90, (5,5))
print(c)

[[59 77 76 83 69]
 [26 76 66 72 42]
 [47 71 84 34 86]
 [47 66 58 54 53]
 [57 66 39 50 39]]


In [37]:
#array dimentions
print(c.shape)


(5, 5)


In [38]:
#number of dimenstions
print(c.ndim)

2


In [39]:
#number of elements in the array
print(c.size)

25


In [40]:
#checking the data type of the vlaue sin array
print(c.dtype)

int64


mathematical operations on Numpy Array

In [43]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]
print(list1 + list2) #here it is not adding the elements

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [57]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))
print(a)
print(b)

[[6 2 4]
 [4 6 0]
 [2 9 4]]
[[18 13 17]
 [17 14 10]
 [17 19 15]]


In [58]:
print(a+b)

print(a-b)
print(a*b)
print(a/b)

[[24 15 21]
 [21 20 10]
 [19 28 19]]
[[-12 -11 -13]
 [-13  -8 -10]
 [-15 -10 -11]]
[[108  26  68]
 [ 68  84   0]
 [ 34 171  60]]
[[0.33333333 0.15384615 0.23529412]
 [0.23529412 0.42857143 0.        ]
 [0.11764706 0.47368421 0.26666667]]


In [59]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[24 15 21]
 [21 20 10]
 [19 28 19]]
[[-12 -11 -13]
 [-13  -8 -10]
 [-15 -10 -11]]
[[108  26  68]
 [ 68  84   0]
 [ 34 171  60]]
[[0.33333333 0.15384615 0.23529412]
 [0.23529412 0.42857143 0.        ]
 [0.11764706 0.47368421 0.26666667]]


array manipulation

In [60]:
array = np.random.randint(0,10, (2,3))
print(array)
print(array.shape)

[[9 3 2]
 [6 6 1]]
(2, 3)


In [61]:
#transpose
trans = np.transpose(array)

In [63]:
print(trans)
print(trans.shape)

[[9 6]
 [3 6]
 [2 1]]
(3, 2)


In [64]:
trans2 = array.T
print(trans2)
print(trans2.shape)

[[9 6]
 [3 6]
 [2 1]]
(3, 2)


In [65]:
#reshaping an array
a = np.random.randint(0, 10 , (2,3))
print(a)
print(a.shape)

[[7 9 1]
 [8 0 5]]
(2, 3)


In [66]:
b = a.reshape(3,2)

In [67]:
print(b)
print(b.shape)

[[7 9]
 [1 8]
 [0 5]]
(3, 2)
